### ISSUE TITLE
Add security question and forget password function

### ISSUE THREAD

**Issue by ghost** [eirikvaa/tdt4237-2019-group05#17]
When users register, they need to choose answers of some security questions(Examples of security questions can be found at https://docs.whmcs.com/Security_Questions). The answers of the security question will be saved in the system. If a user forgets When users register, they need to choose answers of some security questions(Examples of security questions can be found at https://docs.whmcs.com/Security_Questions). The answers of the security question will be saved in the system. If a user forgets the password, the user can click the forget pass-word link. Then, the user needs to type in correct email address. If the email address is valid, his/her chosen security question will be displayed. Then, the user needs to fill in the answer of the security question. If the security question answer is correct, a randomly generated temporary password and a link for letting the user logging in using this password will be sent to theuser’s email address for logging in.the password, the user can click the forget password link. Then, the user needs to type in correct email address. If the email address is valid, his/her chosen security question will be displayed. Then, the user needs to fill in the answer of the security question. If the security question answer is correct, a randomly generated temporary password and a link for letting the user logging in using this password will be sent to the user’s email address for logging in.

**Comment by eirikvaa** [comment]
Implemented in #31.
