### ISSUE TITLE
Add reset password function

### ISSUE THREAD

**Issue by ghost** [eirikvaa/tdt4237-2019-group05#18]
Follow-up with the forget password function, when a user logs in using the temporary password, a web page will show to force the user resetting his/her password. The user needs to type in the temporary password, new password, and the new password again. If the temporary password is correct and the typed in and re-typed in password matches, the new password will be saved in the system for later logging in.

**Comment by Mkohm** [comment]
The reset password function is added, but needs to be integrated with the temporary password thingy.

**Comment by eirikvaa** [comment]
> The reset password function is added, but needs to be integrated with the temporary password thingy.

Forget password (which sets the user's password to a random password) can be found in #31. Here are what needs to be changed in the aforementioned PR to finish this issue:

- _Don't_ set the new, temporary password when the user resets it (but rather after it is confirmed)
- Redirect the user to the temporary password confirmation page where the user will imput the tempoarry password and the new password twice

**Comment by eirikvaa** [comment]
Should be fixed by #37.
