### ISSUE TITLE
Broken Access Control

### ISSUE THREAD

**Issue by ghost** [eirikvaa/tdt4237-2019-group05#2]
Users may open uploaded project files that they do not have permissions for, by enteringthe URL directly.

**Comment by Mkohm** [comment]
links like this:
http://127.0.0.1:8000/media/uploads/tasks/1/test.sh

**Comment by Sydpy** [comment]
I wonder if mangling the filenames when uploading would be an acceptable fix for this. This way non-participants could not be able to guess the filename and enter the appropriate URL, they would have to bruteforce, and we can use rate-limitation to prevent it from succeeding. What are your thoughts on this @Mkohm @ohodegaa @eirikvaa ?

**Comment by Mkohm** [comment]
I think randomized filenames is good enough for this! At least it sound way much simpler to implement!
